-- Create campaign_research_insights table for caching research agent insights
-- This stores insights generated by research agents (keyword, topical-map, hashtag-generator, etc.)
-- as "raw data" associated with campaigns to avoid re-calling the LLM

CREATE TABLE IF NOT EXISTS campaign_research_insights (
    id INT AUTO_INCREMENT PRIMARY KEY,
    campaign_id VARCHAR(255) NOT NULL,
    agent_type VARCHAR(50) NOT NULL,
    insights_text TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_campaign_id (campaign_id),
    INDEX idx_agent_type (agent_type),
    INDEX idx_campaign_agent (campaign_id, agent_type),
    UNIQUE KEY unique_campaign_agent (campaign_id, agent_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

