name: Deploy Backend to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/vernal-agents-post-v0
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart vernal-agents
            sleep 5
            curl -f http://localhost:8000/health || exit 1
            curl -f http://localhost:8000/version || exit 1
            echo "$(date) - Backend deployed via GitHub Actions, commit: $(git rev-parse HEAD)" >> ~/vernal_agents_deploy.log
