name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  EC2_INSTANCE_ID: i-02746733e24e4b970
  EC2_USER: ubuntu
  EC2_HOST: 34.229.14.177

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ env.EC2_HOST }}
        username: ${{ env.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Navigate to the application directory
          cd /home/ubuntu/vernal-post-v0
          
          # Pull latest changes
          git pull origin main
          
          # Install dependencies
          npm install -g pnpm
          pnpm install
          
          # Build the application
          pnpm run build
          
          # Restart the application
          sudo systemctl restart nextjs-app
          sudo systemctl status nextjs-app
