name: Test Agents EC2 Connection

on:
  push:
    branches: [ "main" ]

env:
  AGENTS_EC2_USER: ubuntu
  AGENTS_EC2_HOST: "34.204.6.126"

permissions:
  contents: read

jobs:
  test:
    name: Test Agents Connection
    runs-on: ubuntu-latest

    steps:
    - name: Test Agents EC2 Connection
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ env.AGENTS_EC2_HOST }}
        username: ${{ env.AGENTS_EC2_USER }}
        key: ${{ secrets.AGENTS_EC2_SSH_KEY }}
        passphrase: "hah%asf"
        script: |
          echo "Testing Agents EC2 connection..."
          whoami
          pwd
          ls -la
          echo "Agents connection successful!"
